---
title: Compwright.Github.Io
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  demos:
    title: Demos
    output: true
name: CompWright Enterprises
description: Hello, I'm Jonathon Hill. I build things for the web.
avatar: https://secure.gravatar.com/avatar/0954b07694d217460222ae1dc5fa9c40?size=200
footer-links:
  dribbble: 
  email: jonathon@compwright.com
  facebook: 
  flickr: 
  github: compwright
  instagram: 
  linkedin: https://www.linkedin.com/in/jhill9693/
  pinterest: 
  rss: 
  twitter: compwright
  stackoverflow: users/168815/jonathon-hill
  youtube: 
  googleplus: 
disqus: 
google_analytics: UA-36858680-2
url: https://compwright.github.io
baseurl: ''
permalink: "/:title/"
paginate: 5
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
